// Code generated by MockGen. DO NOT EDIT.
// Source: ./src/services/account.go

// Package mock_services is a generated GoMock package.
package mock_services

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/playneta/go-sessions/src/models"
	reflect "reflect"
)

// MockAccount is a mock of Account interface
type MockAccount struct {
	ctrl     *gomock.Controller
	recorder *MockAccountMockRecorder
}

// MockAccountMockRecorder is the mock recorder for MockAccount
type MockAccountMockRecorder struct {
	mock *MockAccount
}

// NewMockAccount creates a new mock instance
func NewMockAccount(ctrl *gomock.Controller) *MockAccount {
	mock := &MockAccount{ctrl: ctrl}
	mock.recorder = &MockAccountMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAccount) EXPECT() *MockAccountMockRecorder {
	return m.recorder
}

// Register mocks base method
func (m *MockAccount) Register(email, password string) (*models.User, error) {
	ret := m.ctrl.Call(m, "Register", email, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register
func (mr *MockAccountMockRecorder) Register(email, password interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAccount)(nil).Register), email, password)
}

// Authorize mocks base method
func (m *MockAccount) Authorize(email, password string) (*models.User, error) {
	ret := m.ctrl.Call(m, "Authorize", email, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authorize indicates an expected call of Authorize
func (mr *MockAccountMockRecorder) Authorize(email, password interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authorize", reflect.TypeOf((*MockAccount)(nil).Authorize), email, password)
}

// CreateMessage mocks base method
func (m *MockAccount) CreateMessage(user models.User, receiverEmail, text string) (*models.Message, error) {
	ret := m.ctrl.Call(m, "CreateMessage", user, receiverEmail, text)
	ret0, _ := ret[0].(*models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMessage indicates an expected call of CreateMessage
func (mr *MockAccountMockRecorder) CreateMessage(user, receiverEmail, text interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockAccount)(nil).CreateMessage), user, receiverEmail, text)
}

// History mocks base method
func (m *MockAccount) History(user models.User) ([]models.Message, error) {
	ret := m.ctrl.Call(m, "History", user)
	ret0, _ := ret[0].([]models.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History
func (mr *MockAccountMockRecorder) History(user interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockAccount)(nil).History), user)
}
